name: 'Build and publish release'

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish-release:
    runs-on: windows-latest
    permissions:
      contents: write
    if: github.event_name == 'push'
    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Build
        run: msbuild WireSockUI/WireSockUI.csproj -t:rebuild -verbosity:minimal -property:Configuration=Release

      - name: Package Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'WireSockUI-${{ github.ref_name }}.zip'
          directory: 'bin\exe\x64\Release'
          exclusions: '*.pdb'

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'bin\exe\x64\Release\WireSockUI-${{ github.ref_name }}.zip'
          name: 'WireSockUI-${{ github.ref_name }}'
          token: ${{ secrets.GITHUB_TOKEN }}
